service: s3-serverless-uploader

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  apiName: s3-serverless-uploader
  stage: ${opt:stage, 'dev3'}
  versionFunctions: false

functions:
  cache_clear:
    region: ap-northeast-1
    runtime: go1.x
    handler: bin/cache_clear
    events:
      - s3:
          bucket: assets.yukpiz.me
          event: s3:ObjectCreated:*
  image_proxy:
    region: us-east-1
    runtime: nodejs10.x
    handler: functions/image_proxy/index.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin: s3://assets.yukpiz.me.s3.amazonaws.com